[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
optimizer_runs = 1000000
verbosity = 1

[profile.ci]
fuzz_runs = 100_000
verbosity = 4

[rpc_endpoints]
mainnet = "https://eth.llamarpc.com"
goerli = "https://rpc.ankr.com/eth_goerli"
hyperspace = "https://filecoin-hyperspace.chainup.net/rpc/v1"
sepolia = "https://api.sepolia.kroma.network"
orderlydev = "https://testnet-fuji-rpc-1.orderly.network/ext/bc/fVgSf4ruGhwvEMd8z6dRwsH6XgRaq31wxN4tRhZPN6rWYhjVt/rpc"

[etherscan]
mainnet = { key = "${ETHERSCAN_KEY}" }
goerli = { key = "${ETHERSCAN_KEY}", url = "https://api-goerli.etherscan.io/api" }
sepolia = { key = "${ETHERSCAN_KEY}", url = "https://api-sepolia.etherscan.io/api" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
